include: package:very_good_analysis/analysis_options.yaml

analyzer:
  errors:
    # Promover warnings críticos para erro (bloqueia build)
    inference_failure_on_function_invocation: error
    inference_failure_on_instance_creation: error
    inference_failure_on_untyped_parameter: error
    strict_raw_type: error
    unused_import: error
    
    # Rebaixar info para warning (ainda alerta mas não bloqueia)
    public_member_api_docs: ignore # Temporário: 359 issues
    avoid_redundant_argument_values: ignore # Temporário: 73 issues
    cascade_invocations: ignore # Temporário: 45 issues
    flutter_style_todos: ignore # Temporário: 17 issues
    
    # Manter warnings importantes
    use_build_context_synchronously: warning
    deprecated_member_use: warning
    unawaited_futures: warning

linter:
  rules:
    # Regras extras que eu sempre uso em projetos elite (2025)
    # always_specify_types: true # Removido: conflita com omit_local_variable_types
    prefer_single_quotes: true
    require_trailing_commas: true
    unnecessary_await_in_return: true
    unnecessary_lambdas: true
    # prefer_relative_imports: true # Removido: conflita com always_use_package_imports
    avoid_relative_lib_imports: false
    lines_longer_than_80_chars: false # aceitável em Flutter
    avoid_print: true
    avoid_dynamic_calls: true
    use_build_context_synchronously: true
    use_key_in_widget_constructors: false
    
    # Desabilitar temporariamente (Task 1.2 - Fase 1)
    directives_ordering: false # 68 issues - reabilitar depois
    use_setters_to_change_properties: false # 22 issues
