import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:freezed_annotation/freezed_annotation.dart';

part 'message_new_entity.freezed.dart';
part 'message_new_entity.g.dart';

/// Status de entrega da mensagem
enum MessageDeliveryStatus {
  /// Mensagem enviando (otimistic UI)
  sending,

  /// Mensagem enviada para o servidor
  sent,

  /// Mensagem entregue ao dispositivo do destinatário
  delivered,

  /// Mensagem lida pelo destinatário
  read,

  /// Falha no envio
  failed,
}

/// Tipo de mensagem
enum MessageType {
  /// Mensagem de texto simples
  text,

  /// Mensagem com imagem
  image,

  /// Mensagem de sistema (ex: "Fulano entrou na conversa")
  system,

  /// Mensagem deletada
  deleted,

  /// Post compartilhado (encaminhado de outra tela)
  sharedPost,
}

/// Domain entity para Mensagem individual - Nova implementação
///
/// Suporta:
/// - Texto com emojis
/// - Imagens
/// - Reações (múltiplas por usuário)
/// - Reply (responder mensagem)
/// - Edição de mensagem
/// - Status de entrega (sent/delivered/read)
/// - Mensagens de sistema
/// - Soft delete (para mim / para todos)
@freezed
class MessageNewEntity with _$MessageNewEntity {
  const MessageNewEntity._();

  const factory MessageNewEntity({
    /// ID único da mensagem no Firestore
    required String id,

    /// ID da conversa pai
    required String conversationId,

    /// UID do remetente (Firebase Auth)
    required String senderId,

    /// ProfileId do remetente
    required String senderProfileId,

    /// Nome do remetente (desnormalizado para performance)
    String? senderName,

    /// Foto do remetente (desnormalizado para performance)
    String? senderPhotoUrl,

    /// Conteúdo textual da mensagem
    required String text,

    /// URL da imagem (se houver)
    String? imageUrl,

    /// Tipo da mensagem
    @Default(MessageType.text) MessageType type,

    /// Status de entrega
    @Default(MessageDeliveryStatus.sending) MessageDeliveryStatus status,

    /// Timestamp de criação
    required DateTime createdAt,

    /// Timestamp de edição (null se nunca editado)
    DateTime? editedAt,

    /// Se a mensagem foi editada
    @Default(false) bool isEdited,

    /// Reações: Map<profileId, emoji>
    @Default({}) Map<String, String> reactions,

    /// Dados da mensagem que está sendo respondida
    MessageReplyData? replyTo,

    /// Lista de profileIds que deletaram a mensagem "para mim"
    @Default([]) List<String> deletedForProfiles,

    /// Se a mensagem foi deletada para todos
    @Default(false) bool deletedForEveryone,

    /// Texto original (antes de deletar para todos)
    String? originalText,

    /// Metadados extras (extensível)
    @Default({}) Map<String, dynamic> metadata,

    /// [GRUPOS] Lista de profileIds que receberam a mensagem (delivered)
    /// Em grupos, a mensagem só mostra "delivered" quando TODOS receberam
    @Default([]) List<String> receivedBy,

    /// [GRUPOS] Lista de profileIds que leram a mensagem (read)
    /// Em grupos, a mensagem só mostra "read" quando TODOS leram
    @Default([]) List<String> readBy,
  }) = _MessageNewEntity;

  /// From Firestore Document
  factory MessageNewEntity.fromFirestore(
    DocumentSnapshot<Map<String, dynamic>> snapshot, {
    String? conversationId,
  }) {
    final data = snapshot.data();
    if (data == null) {
      throw Exception('MessageNewEntity: data is null for ${snapshot.id}');
    }

    return MessageNewEntity(
      id: snapshot.id,
      conversationId: conversationId ?? data['conversationId'] as String? ?? '',
      senderId: data['senderId'] as String? ?? '',
      senderProfileId: data['senderProfileId'] as String? ?? data['senderId'] as String? ?? '',
      senderName: data['senderName'] as String?,
      senderPhotoUrl: data['senderPhotoUrl'] as String?,
      text: data['text'] as String? ?? '',
      imageUrl: data['imageUrl'] as String?,
      type: _parseMessageType(data['type']),
      status: _parseDeliveryStatus(data['status']),
      createdAt: (data['createdAt'] as Timestamp?)?.toDate() ?? DateTime.now(),
      editedAt: (data['editedAt'] as Timestamp?)?.toDate(),
      isEdited: data['isEdited'] as bool? ?? false,
      reactions: _parseReactions(data['reactions']),
      replyTo: data['replyTo'] != null
          ? MessageReplyData.fromMap(data['replyTo'] as Map<String, dynamic>)
          : null,
      deletedForProfiles:
          (data['deletedForProfiles'] as List<dynamic>?)?.cast<String>() ?? [],
      deletedForEveryone: data['deletedForEveryone'] as bool? ?? false,
      originalText: data['originalText'] as String?,
      metadata: (data['metadata'] as Map<String, dynamic>?) ?? {},
      receivedBy: (data['receivedBy'] as List<dynamic>?)?.cast<String>() ?? [],
      readBy: (data['readBy'] as List<dynamic>?)?.cast<String>() ?? [],
    );
  }

  /// From JSON - generated by freezed
  factory MessageNewEntity.fromJson(Map<String, dynamic> json) =>
      _$MessageNewEntityFromJson(json);

  /// Parse MessageType safely
  static MessageType _parseMessageType(dynamic data) {
    if (data == null) return MessageType.text;
    if (data is String) {
      return MessageType.values.firstWhere(
        (e) => e.name == data,
        orElse: () => MessageType.text,
      );
    }
    return MessageType.text;
  }

  /// Parse MessageDeliveryStatus safely
  static MessageDeliveryStatus _parseDeliveryStatus(dynamic data) {
    if (data == null) return MessageDeliveryStatus.sent;
    if (data is String) {
      return MessageDeliveryStatus.values.firstWhere(
        (e) => e.name == data,
        orElse: () => MessageDeliveryStatus.sent,
      );
    }
    return MessageDeliveryStatus.sent;
  }

  /// Parse reactions map safely
  static Map<String, String> _parseReactions(dynamic data) {
    if (data == null) return {};
    if (data is! Map) return {};
    return Map<String, String>.from(
      data.map((k, v) => MapEntry(k.toString(), v.toString())),
    );
  }

  // ============================================
  // GETTERS ÚTEIS
  // ============================================

  /// Verifica se é mensagem de imagem
  bool get hasImage => imageUrl != null && imageUrl!.isNotEmpty;

  /// Verifica se tem texto
  bool get hasText => text.isNotEmpty;

  /// Verifica se é uma resposta a outra mensagem
  bool get isReply => replyTo != null;

  /// Verifica se tem reações
  bool get hasReactions => reactions.isNotEmpty;

  /// Verifica se é mensagem de sistema
  bool get isSystemMessage => type == MessageType.system;

  /// Verifica se é post compartilhado
  bool get isSharedPost => type == MessageType.sharedPost;

  /// Verifica se está deletada para todos
  bool get isDeletedForEveryone => deletedForEveryone || type == MessageType.deleted;

  /// Verifica se está deletada para um perfil específico
  bool isDeletedForProfile(String profileId) {
    return deletedForProfiles.contains(profileId) || isDeletedForEveryone;
  }

  /// Verifica se é do próprio usuário
  bool isMine(String currentProfileId) {
    return senderProfileId == currentProfileId;
  }

  /// Preview da mensagem (para lista de conversas)
  String get preview {
    if (isDeletedForEveryone) return '🚫 Mensagem apagada';
    if (type == MessageType.system) return text;
    if (isSharedPost) return '📌 Compartilhou um post';
    if (hasImage && !hasText) return '📷 Foto';
    if (hasText) {
      final trimmed = text.trim();
      return trimmed.length > 50 ? '${trimmed.substring(0, 50)}...' : trimmed;
    }
    return '';
  }

  /// Retorna lista de emojis de reações únicas
  List<String> get uniqueReactionEmojis {
    return reactions.values.toSet().toList();
  }

  /// Retorna contagem de cada reação
  Map<String, int> get reactionCounts {
    final counts = <String, int>{};
    for (final emoji in reactions.values) {
      counts[emoji] = (counts[emoji] ?? 0) + 1;
    }
    return counts;
  }

  /// Retorna a reação de um perfil específico (ou null)
  String? getReactionByProfile(String profileId) {
    return reactions[profileId];
  }

  /// Retorna lista de profileIds que reagiram com um emoji específico
  List<String> getProfilesForReaction(String emoji) {
    return reactions.entries
        .where((e) => e.value == emoji)
        .map((e) => e.key)
        .toList();
  }

  /// ✅ Verifica se a mensagem pode ser editada (até 15 minutos após envio)
  bool canEdit(String currentProfileId) {
    // Apenas o autor pode editar
    if (senderProfileId != currentProfileId) return false;
    
    // Mensagens deletadas não podem ser editadas
    if (isDeletedForEveryone) return false;
    
    // Mensagens de sistema não podem ser editadas
    if (isSystemMessage) return false;
    
    // Limite de 15 minutos
    final now = DateTime.now();
    final timeSinceCreation = now.difference(createdAt);
    return timeSinceCreation.inMinutes < 15;
  }

  /// ✅ Retorna o tempo restante para edição em minutos (null se não pode editar)
  int? editTimeRemainingMinutes(String currentProfileId) {
    if (!canEdit(currentProfileId)) return null;
    
    final now = DateTime.now();
    final elapsed = now.difference(createdAt).inMinutes;
    return 15 - elapsed;
  }

  // ============================================
  // VALIDATION
  // ============================================

  /// Valida mensagem antes de enviar
  static String? validate(String text, String? imageUrl) {
    if (text.trim().isEmpty && (imageUrl == null || imageUrl.isEmpty)) {
      return 'Mensagem não pode ser vazia';
    }
    if (text.length > 2000) {
      return 'Mensagem muito longa (máximo 2000 caracteres)';
    }
    return null;
  }

  /// Sanitiza texto (preserva emojis, remove apenas caracteres de controle)
  static String sanitize(String text) {
    var sanitized = text.trim();
    // Remove múltiplas quebras de linha consecutivas (mantém 1)
    sanitized = sanitized.replaceAll(RegExp(r'\s*\n{3,}\s*'), '\n\n');
    // Remove caracteres de controle C0 (exceto \n e \t)
    sanitized =
        sanitized.replaceAll(RegExp(r'[\u0000-\u0008\u000B-\u001F\u007F]'), '');
    return sanitized;
  }

  // ============================================
  // TO FIRESTORE
  // ============================================

  /// To Firestore Document
  Map<String, dynamic> toFirestore() {
    return {
      'conversationId': conversationId,
      'senderId': senderId,
      'senderProfileId': senderProfileId,
      if (senderName != null) 'senderName': senderName,
      if (senderPhotoUrl != null) 'senderPhotoUrl': senderPhotoUrl,
      'text': text,
      if (imageUrl != null) 'imageUrl': imageUrl,
      'type': type.name,
      'status': status.name,
      'createdAt': Timestamp.fromDate(createdAt),
      if (editedAt != null) 'editedAt': Timestamp.fromDate(editedAt!),
      'isEdited': isEdited,
      'reactions': reactions,
      if (replyTo != null) 'replyTo': replyTo!.toMap(),
      'deletedForProfiles': deletedForProfiles,
      'deletedForEveryone': deletedForEveryone,
      if (originalText != null) 'originalText': originalText,
      if (metadata.isNotEmpty) 'metadata': metadata,
      if (receivedBy.isNotEmpty) 'receivedBy': receivedBy,
      if (readBy.isNotEmpty) 'readBy': readBy,
    };
  }

  // ============================================
  // GETTERS PARA GRUPOS
  // ============================================

  /// [GRUPOS] Calcula status de delivery baseado em receivedBy/readBy
  /// Para exibir corretamente em grupos, considerando todos os participantes
  MessageDeliveryStatus getGroupStatus(List<String> otherParticipantIds) {
    // Se não há outros participantes, usa status padrão
    if (otherParticipantIds.isEmpty) return status;
    
    // Verifica se TODOS leram
    final allRead = otherParticipantIds.every((id) => readBy.contains(id));
    if (allRead) return MessageDeliveryStatus.read;
    
    // Verifica se TODOS receberam
    final allReceived = otherParticipantIds.every((id) => receivedBy.contains(id));
    if (allReceived) return MessageDeliveryStatus.delivered;
    
    // Caso contrário, usa status padrão (sent)
    return status == MessageDeliveryStatus.read || status == MessageDeliveryStatus.delivered
        ? MessageDeliveryStatus.sent
        : status;
  }

  /// [GRUPOS] Verifica se todos os participantes receberam
  bool allReceivedBy(List<String> otherParticipantIds) {
    return otherParticipantIds.every((id) => receivedBy.contains(id));
  }

  /// [GRUPOS] Verifica se todos os participantes leram
  bool allReadBy(List<String> otherParticipantIds) {
    return otherParticipantIds.every((id) => readBy.contains(id));
  }
}

/// Dados da mensagem que está sendo respondida
@freezed
class MessageReplyData with _$MessageReplyData {
  const MessageReplyData._();

  const factory MessageReplyData({
    /// ID da mensagem original
    required String messageId,

    /// Texto da mensagem original (preview)
    required String text,

    /// ProfileId do autor da mensagem original
    required String senderProfileId,

    /// Nome do autor (desnormalizado)
    String? senderName,

    /// URL da imagem (se a mensagem original tinha imagem)
    String? imageUrl,
  }) = _MessageReplyData;

  /// From map
  factory MessageReplyData.fromMap(Map<String, dynamic> map) {
    return MessageReplyData(
      messageId: map['messageId'] as String? ?? '',
      text: map['text'] as String? ?? '',
      senderProfileId: map['senderProfileId'] as String? ?? '',
      senderName: map['senderName'] as String?,
      imageUrl: map['imageUrl'] as String?,
    );
  }

  factory MessageReplyData.fromJson(Map<String, dynamic> json) =>
      _$MessageReplyDataFromJson(json);

  /// To map
  Map<String, dynamic> toMap() {
    return {
      'messageId': messageId,
      'text': text,
      'senderProfileId': senderProfileId,
      if (senderName != null) 'senderName': senderName,
      if (imageUrl != null) 'imageUrl': imageUrl,
    };
  }

  /// Preview do texto (truncado)
  String get preview {
    if (imageUrl != null && text.isEmpty) return '📷 Foto';
    if (text.length > 50) return '${text.substring(0, 50)}...';
    return text;
  }
}
