import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:freezed_annotation/freezed_annotation.dart';

part 'message_entity.freezed.dart';
part 'message_entity.g.dart';

/// Domain entity para Mensagem individual
/// Suporta texto, imagens, reações e replies (responder)
@freezed
class MessageEntity with _$MessageEntity {
  const MessageEntity._();

  const factory MessageEntity({
    required String messageId,
    required String senderId,
    required String senderProfileId,
    required String text,
    required DateTime timestamp,
    String? imageUrl,
    MessageReplyEntity? replyTo,
    @Default({}) Map<String, String> reactions,
    @Default(false) bool read,
  }) = _MessageEntity;

  /// From Firestore Document
  factory MessageEntity.fromFirestore(
    DocumentSnapshot<Map<String, dynamic>> snapshot,
  ) {
    final data = snapshot.data();
    if (data == null) {
      throw Exception('Message data is null');
    }

    return MessageEntity(
      messageId: snapshot.id,
      senderId: data['senderId'] as String? ?? '',
      senderProfileId: data['senderProfileId'] as String? ??
          data['senderId'] as String? ??
          '',
      text: data['text'] as String? ?? '',
      imageUrl: data['imageUrl'] as String?,
      replyTo: data['replyTo'] != null
          ? MessageReplyEntity.fromMap(data['replyTo'] as Map<String, dynamic>)
          : null,
      reactions: Map<String, String>.from((data['reactions'] as Map?)
              ?.map((k, v) => MapEntry(k.toString(), v.toString())) ??
          {}),
      timestamp: (data['timestamp'] as Timestamp?)?.toDate() ?? DateTime.now(),
      read: data['read'] as bool? ?? false,
    );
  }

  /// From JSON - generated by freezed
  factory MessageEntity.fromJson(Map<String, dynamic> json) =>
      _$MessageEntityFromJson(json);

  /// Getters úteis
  bool get hasImage => imageUrl != null && imageUrl!.isNotEmpty;
  bool get hasText => text.isNotEmpty;
  bool get isReply => replyTo != null;
  bool get hasReactions => reactions.isNotEmpty;

  /// Preview da mensagem (para lista de conversas)
  String get preview {
    if (hasImage && !hasText) return '📷 Foto';
    if (hasText) return text.length > 50 ? '${text.substring(0, 50)}...' : text;
    return '';
  }

  /// Valida mensagem antes de enviar
  static String? validate(String text, String? imageUrl) {
    if (text.trim().isEmpty && imageUrl == null) {
      return 'Mensagem não pode ser vazia';
    }
    if (text.length > 1000) {
      return 'Mensagem muito longa (máximo 1000 caracteres)';
    }
    return null;
  }

  /// Sanitiza texto (preserva emojis, remove apenas controle chars)
  static String sanitize(String text) {
    var sanitized = text.trim();
    // Remove múltiplas quebras de linha consecutivas
    sanitized = sanitized.replaceAll(RegExp(r'\s*\n{2,}\s*'), '\n');
    // Remove caracteres de controle (mas preserva emojis)
    sanitized = sanitized.replaceAll(RegExp(r'[\u0000-\u001F\u007F]'), '');
    return sanitized;
  }

  /// To Firestore Document
  Map<String, dynamic> toFirestore() {
    return {
      'senderId': senderId,
      'senderProfileId': senderProfileId,
      'text': text,
      if (imageUrl != null) 'imageUrl': imageUrl,
      if (replyTo != null) 'replyTo': replyTo!.toMap(),
      'reactions': reactions,
      'timestamp': Timestamp.fromDate(timestamp),
      'read': read,
    };
  }

  /// To JSON - generated by freezed
  // toJson() is already generated by freezed
}

/// Modelo de reply (resposta a uma mensagem)
@freezed
class MessageReplyEntity with _$MessageReplyEntity {
  const MessageReplyEntity._();

  const factory MessageReplyEntity({
    required String messageId,
    required String text,
    required String senderId,
    String? senderProfileId,
  }) = _MessageReplyEntity;

  factory MessageReplyEntity.fromMap(Map<String, dynamic> map) {
    return MessageReplyEntity(
      messageId: map['messageId'] as String? ?? '',
      text: map['text'] as String? ?? '',
      senderId: map['senderId'] as String? ?? '',
      senderProfileId: map['senderProfileId'] as String?,
    );
  }

  factory MessageReplyEntity.fromJson(Map<String, dynamic> json) =>
      _$MessageReplyEntityFromJson(json);

  /// Compatibility method with legacy code
  Map<String, dynamic> toMap() {
    return {
      'messageId': messageId,
      'text': text,
      'senderId': senderId,
      if (senderProfileId != null) 'senderProfileId': senderProfileId,
    };
  }
}
