// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps - DEV Environment.
///
/// Example:
/// ```dart
/// import 'firebase_options_dev.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // TODO: Replace with your DEV Firebase project configuration

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBPov3Sy9P2M3u5ckWW4fqWdMuo7OBHNA',
    appId: '1:963929089370:android:9982e7cff7a65685ec7f63',
    messagingSenderId: '963929089370',
    projectId: 'wegig-dev',
    storageBucket: 'wegig-dev.firebasestorage.app',
  );

  // Run: flutterfire configure --project=to-sem-banda-dev --out=lib/firebase_options_dev.dart

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAf6EMmKIke4UX_PH9L78dIhQjCZyPiO1s',
    appId: '1:963929089370:ios:c9a1e302fc589b5fec7f63',
    messagingSenderId: '963929089370',
    projectId: 'wegig-dev',
    storageBucket: 'wegig-dev.firebasestorage.app',
    iosBundleId: 'com.wegig.wegig.dev',
  );
}
