// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3Rq-Fmlsrwn-fywriTBp7xZsOo7i5fyQ',
    appId: '1:278498777601:web:8a281dd57bf8dfce9ebe00',
    messagingSenderId: '278498777601',
    projectId: 'wegig-dev',
    authDomain: 'wegig-dev.firebaseapp.com',
    storageBucket: 'wegig-dev.firebasestorage.app',
    measurementId: 'G-XLW5KQJDH0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_QxHROqFRoIzCHBK_NFxu-GG6uMNS0uk',
    appId: '1:278498777601:android:3cb8437111dd6c5f9ebe00',
    messagingSenderId: '278498777601',
    projectId: 'wegig-dev',
    storageBucket: 'wegig-dev.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAe_WwvD3nN-VJlMZf2L_BRpIx-ne3P_-0',
    appId: '1:278498777601:ios:cdeec8b4da7c657a9ebe00',
    messagingSenderId: '278498777601',
    projectId: 'wegig-dev',
    storageBucket: 'wegig-dev.firebasestorage.app',
    iosBundleId: 'com.example.toSemBanda',
  );
}
