// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps - PRODUCTION Environment.
///
/// Example:
/// ```dart
/// import 'firebase_options_prod.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // Production Firebase project (to-sem-banda-83e19)
  // ⚠️ CRITICAL: These credentials point to the PROD Firebase project
  // DO NOT use wegig-dev credentials here!

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_QxHROqFRoIzCHBK_NFxu-GG6uMNS0uk',
    appId: '1:278498777601:android:b0c425b0b641d9589ebe00',
    messagingSenderId: '278498777601',
    projectId: 'to-sem-banda-83e19',
    storageBucket: 'to-sem-banda-83e19.firebasestorage.app',
  );

  // This is the current production project - keep these credentials

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAe_WwvD3nN-VJlMZf2L_BRpIx-ne3P_-0',
    appId: '1:278498777601:ios:79de6105dc4a151f9ebe00',
    messagingSenderId: '278498777601',
    projectId: 'to-sem-banda-83e19',
    storageBucket: 'to-sem-banda-83e19.firebasestorage.app',
    iosClientId:
        '278498777601-qlukbsv2s4aukhlh34v3icqsjj0ho2k7.apps.googleusercontent.com',
    iosBundleId: 'com.wegig.wegig',
  );
}
