// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps - STAGING Environment.
///
/// Example:
/// ```dart
/// import 'firebase_options_staging.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // TODO: Replace with your STAGING Firebase project configuration

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSdKys9izCKHrkGlxlNCnuTqcU7Xjcoaw',
    appId: '1:27906769066:android:1dfb4c1cff7bbfbdbcd0d3',
    messagingSenderId: '27906769066',
    projectId: 'wegig-staging',
    storageBucket: 'wegig-staging.firebasestorage.app',
  );

  // Run: flutterfire configure --project=to-sem-banda-staging --out=lib/firebase_options_staging.dart

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAca3GkAy6euZ0QeO55TZ71gFQlM1c0c5Y',
    appId: '1:27906769066:ios:e18b9605552d60e5bcd0d3',
    messagingSenderId: '27906769066',
    projectId: 'wegig-staging',
    storageBucket: 'wegig-staging.firebasestorage.app',
    iosBundleId: 'com.wegig.wegig',
  );
}
